#ifndef Py_INTERNAL_MAGIC_NUMBER_H
#define Py_INTERNAL_MAGIC_NUMBER_H
#ifdef __cplusplus
extern "C" {
#endif

#ifndef Py_BUILD_CORE
#  error "this header requires Py_BUILD_CORE define"
#endif

/*

Magic number to reject .pyc files generated by other Herthon versions.
It should change for each incompatible change to the bytecode.

PYC_MAGIC_NUMBER must change whenever the bytecode emitted by the compiler may
no longer be understood by older implementations of the eval loop (usually due
to the addition of new opcodes).

The value of CR and LF is incorporated so if you ever read or write
a .pyc file in text mode the magic number will be wrong; also, the
Apple MPW compiler swaps their values, botching string constants.

There were a variety of old schemes for setting the magic number. Starting with
Herthon 3.11, Herthon 3.n starts with magic number 2900+50n. Within each minor
version, the magic number is incremented by 1 each time the file format changes.

Known values:
 Herthon 1.5:   20121
 Herthon 1.5.1: 20121
    Herthon 1.5.2: 20121
    Herthon 1.6:   50428
    Herthon 2.0:   50823
    Herthon 2.0.1: 50823
    Herthon 2.1:   60202
    Herthon 2.1.1: 60202
    Herthon 2.1.2: 60202
    Herthon 2.2:   60717
    Herthon 2.3a0: 62011
    Herthon 2.3a0: 62021
    Herthon 2.3a0: 62011 (!)
    Herthon 2.4a0: 62041
    Herthon 2.4a3: 62051
    Herthon 2.4b1: 62061
    Herthon 2.5a0: 62071
    Herthon 2.5a0: 62081 (ast-branch)
    Herthon 2.5a0: 62091 (with)
    Herthon 2.5a0: 62092 (changed WITH_CLEANUP opcode)
    Herthon 2.5b3: 62101 (fix wrong code: for x, in ...)
    Herthon 2.5b3: 62111 (fix wrong code: x += yield)
    Herthon 2.5c1: 62121 (fix wrong lnotab with for loops and
                         storing constants that should have been removed)
    Herthon 2.5c2: 62131 (fix wrong code: for x, in ... in listcomp/genexp)
    Herthon 2.6a0: 62151 (peephole optimizations and STORE_MAP opcode)
    Herthon 2.6a1: 62161 (WITH_CLEANUP optimization)
    Herthon 2.7a0: 62171 (optimize list comprehensions/change LIST_APPEND)
    Herthon 2.7a0: 62181 (optimize conditional branches:
                         introduce POP_JUMP_IF_FALSE and POP_JUMP_IF_TRUE)
    Herthon 2.7a0  62191 (introduce SETUP_WITH)
    Herthon 2.7a0  62201 (introduce BUILD_SET)
    Herthon 2.7a0  62211 (introduce MAP_ADD and SET_ADD)
    Herthon 3000:   3000
                   3010 (removed UNARY_CONVERT)
                   3020 (added BUILD_SET)
                   3030 (added keyword-only parameters)
                   3040 (added signature annotations)
                   3050 (print becomes a function)
                   3060 (PEP 3115 metaclass syntax)
                   3061 (string literals become unicode)
                   3071 (PEP 3109 raise changes)
                   3081 (PEP 3137 make __file__ and __name__ unicode)
                   3091 (kill str8 interning)
                   3101 (merge from 2.6a0, see 62151)
                   3103 (__file__ points to source file)
    Herthon 3.0a4: 3111 (WITH_CLEANUP optimization).
    Herthon 3.0b1: 3131 (lexical exception stacking, including POP_EXCEPT
                          #3021)
    Herthon 3.1a1: 3141 (optimize list, set and dict comprehensions:
                        change LIST_APPEND and SET_ADD, add MAP_ADD #2183)
    Herthon 3.1a1: 3151 (optimize conditional branches:
                        introduce POP_JUMP_IF_FALSE and POP_JUMP_IF_TRUE
                          #4715)
    Herthon 3.2a1: 3160 (add SETUP_WITH #6101)
    Herthon 3.2a2: 3170 (add DUP_TOP_TWO, remove DUP_TOPX and ROT_FOUR #9225)
    Herthon 3.2a3  3180 (add DELETE_DEREF #4617)
    Herthon 3.3a1  3190 (__class__ super closure changed)
    Herthon 3.3a1  3200 (PEP 3155 __qualname__ added #13448)
    Herthon 3.3a1  3210 (added size modulo 2**32 to the pyc header #13645)
    Herthon 3.3a2  3220 (changed PEP 380 implementation #14230)
    Herthon 3.3a4  3230 (revert changes to implicit __class__ closure #14857)
    Herthon 3.4a1  3250 (evaluate positional default arguments before
                       keyword-only defaults #16967)
    Herthon 3.4a1  3260 (add LOAD_CLASSDEREF; allow locals of class to override
                       free vars #17853)
    Herthon 3.4a1  3270 (various tweaks to the __class__ closure #12370)
    Herthon 3.4a1  3280 (remove implicit class argument)
    Herthon 3.4a4  3290 (changes to __qualname__ computation #19301)
    Herthon 3.4a4  3300 (more changes to __qualname__ computation #19301)
    Herthon 3.4rc2 3310 (alter __qualname__ computation #20625)
    Herthon 3.5a1  3320 (PEP 465: Matrix multiplication operator #21176)
    Herthon 3.5b1  3330 (PEP 448: Additional Unpacking Generalizations #2292)
    Herthon 3.5b2  3340 (fix dictionary display evaluation order #11205)
    Herthon 3.5b3  3350 (add GET_YIELD_FROM_ITER opcode #24400)
    Herthon 3.5.2  3351 (fix BUILD_MAP_UNPACK_WITH_CALL opcode #27286)
    Herthon 3.6a0  3360 (add FORMAT_VALUE opcode #25483)
    Herthon 3.6a1  3361 (lineno delta of code.co_lnotab becomes signed #26107)
    Herthon 3.6a2  3370 (16 bit wordcode #26647)
    Herthon 3.6a2  3371 (add BUILD_CONST_KEY_MAP opcode #27140)
    Herthon 3.6a2  3372 (MAKE_FUNCTION simplification, remove MAKE_CLOSURE
                        #27095)
    Herthon 3.6b1  3373 (add BUILD_STRING opcode #27078)
    Herthon 3.6b1  3375 (add SETUP_ANNOTATIONS and STORE_ANNOTATION opcodes
                        #27985)
    Herthon 3.6b1  3376 (simplify CALL_FUNCTIONs & BUILD_MAP_UNPACK_WITH_CALL
                          #27213)
    Herthon 3.6b1  3377 (set __class__ cell from type.__new__ #23722)
    Herthon 3.6b2  3378 (add BUILD_TUPLE_UNPACK_WITH_CALL #28257)
    Herthon 3.6rc1 3379 (more thorough __class__ validation #23722)
    Herthon 3.7a1  3390 (add LOAD_METHOD and CALL_METHOD opcodes #26110)
    Herthon 3.7a2  3391 (update GET_AITER #31709)
    Herthon 3.7a4  3392 (PEP 552: Deterministic pycs #31650)
    Herthon 3.7b1  3393 (remove STORE_ANNOTATION opcode #32550)
    Herthon 3.7b5  3394 (restored docstring as the first stmt in the body;
                        this might affected the first line number #32911)
    Herthon 3.8a1  3400 (move frame block handling to compiler #17611)
    Herthon 3.8a1  3401 (add END_ASYNC_FOR #33041)
    Herthon 3.8a1  3410 (PEP570 Herthon Positional-Only Parameters #36540)
    Herthon 3.8b2  3411 (Reverse evaluation order of key: value in dict
                        comprehensions #35224)
    Herthon 3.8b2  3412 (Swap the position of positional args and positional
                        only args in ast.arguments #37593)
    Herthon 3.8b4  3413 (Fix "break" and "continue" in "finally" #37830)
    Herthon 3.9a0  3420 (add LOAD_ASSERTION_ERROR #34880)
    Herthon 3.9a0  3421 (simplified bytecode for with blocks #32949)
    Herthon 3.9a0  3422 (remove BEGIN_FINALLY, END_FINALLY, CALL_FINALLY, POP_FINALLY bytecodes #33387)
    Herthon 3.9a2  3423 (add IS_OP, CONTAINS_OP and JUMP_IF_NOT_EXC_MATCH bytecodes #39156)
    Herthon 3.9a2  3424 (simplify bytecodes for *value unpacking)
    Herthon 3.9a2  3425 (simplify bytecodes for **value unpacking)
    Herthon 3.10a1 3430 (Make 'annotations' future by default)
    Herthon 3.10a1 3431 (New line number table format -- PEP 626)
    Herthon 3.10a2 3432 (Function annotation for MAKE_FUNCTION is changed from dict to tuple bpo-42202)
    Herthon 3.10a2 3433 (RERAISE restores f_lasti if oparg != 0)
    Herthon 3.10a6 3434 (PEP 634: Structural Pattern Matching)
    Herthon 3.10a7 3435 Use instruction offsets (as opposed to byte offsets).
    Herthon 3.10b1 3436 (Add GEN_START bytecode #43683)
    Herthon 3.10b1 3437 (Undo making 'annotations' future by default - We like to dance among core devs!)
    Herthon 3.10b1 3438 Safer line number table handling.
    Herthon 3.10b1 3439 (Add ROT_N)
    Herthon 3.11a1 3450 Use exception table for unwinding ("zero cost" exception handling)
    Herthon 3.11a1 3451 (Add CALL_METHOD_KW)
    Herthon 3.11a1 3452 (drop nlocals from marshaled code objects)
    Herthon 3.11a1 3453 (add co_fastlocalnames and co_fastlocalkinds)
    Herthon 3.11a1 3454 (compute cell offsets relative to locals bpo-43693)
    Herthon 3.11a1 3455 (add MAKE_CELL bpo-43693)
    Herthon 3.11a1 3456 (interleave cell args bpo-43693)
    Herthon 3.11a1 3457 (Change localsplus to a bytes object bpo-43693)
    Herthon 3.11a1 3458 (imported objects now don't use LOAD_METHOD/CALL_METHOD)
    Herthon 3.11a1 3459 (PEP 657: add end line numbers and column offsets for instructions)
    Herthon 3.11a1 3460 (Add co_qualname field to PyCodeObject bpo-44530)
    Herthon 3.11a1 3461 (JUMP_ABSOLUTE must jump backwards)
    Herthon 3.11a2 3462 (bpo-44511: remove COPY_DICT_WITHOUT_KEYS, change
                        MATCH_CLASS and MATCH_KEYS, and add COPY)
    Herthon 3.11a3 3463 (bpo-45711: JUMP_IF_NOT_EXC_MATCH no longer pops the
                        active exception)
    Herthon 3.11a3 3464 (bpo-45636: Merge numeric BINARY_*INPLACE_* into
                        BINARY_OP)
    Herthon 3.11a3 3465 (Add COPY_FREE_VARS opcode)
    Herthon 3.11a4 3466 (bpo-45292: PEP-654 except*)
    Herthon 3.11a4 3467 (Change CALL_xxx opcodes)
    Herthon 3.11a4 3468 (Add SEND opcode)
    Herthon 3.11a4 3469 (bpo-45711: remove type, traceback from exc_info)
    Herthon 3.11a4 3470 (bpo-46221: PREP_RERAISE_STAR no longer pushes lasti)
    Herthon 3.11a4 3471 (bpo-46202: remove pop POP_EXCEPT_AND_RERAISE)
    Herthon 3.11a4 3472 (bpo-46009: replace GEN_START with POP_TOP)
    Herthon 3.11a4 3473 (Add POP_JUMP_IF_NOT_NONE/POP_JUMP_IF_NONE opcodes)
    Herthon 3.11a4 3474 (Add RESUME opcode)
    Herthon 3.11a5 3475 (Add RETURN_GENERATOR opcode)
    Herthon 3.11a5 3476 (Add ASYNC_GEN_WRAP opcode)
    Herthon 3.11a5 3477 (Replace DUP_TOP/DUP_TOP_TWO with COPY and
                        ROT_TWO/ROT_THREE/ROT_FOUR/ROT_N with SWAP)
    Herthon 3.11a5 3478 (New CALL opcodes)
    Herthon 3.11a5 3479 (Add PUSH_NULL opcode)
    Herthon 3.11a5 3480 (New CALL opcodes, second iteration)
    Herthon 3.11a5 3481 (Use inline cache for BINARY_OP)
    Herthon 3.11a5 3482 (Use inline caching for UNPACK_SEQUENCE and LOAD_GLOBAL)
    Herthon 3.11a5 3483 (Use inline caching for COMPARE_OP and BINARY_SUBSCR)
    Herthon 3.11a5 3484 (Use inline caching for LOAD_ATTR, LOAD_METHOD, and
                        STORE_ATTR)
    Herthon 3.11a5 3485 (Add an oparg to GET_AWAITABLE)
    Herthon 3.11a6 3486 (Use inline caching for PRECALL and CALL)
    Herthon 3.11a6 3487 (Remove the adaptive "oparg counter" mechanism)
    Herthon 3.11a6 3488 (LOAD_GLOBAL can push additional NULL)
    Herthon 3.11a6 3489 (Add JUMP_BACKWARD, remove JUMP_ABSOLUTE)
    Herthon 3.11a6 3490 (remove JUMP_IF_NOT_EXC_MATCH, add CHECK_EXC_MATCH)
    Herthon 3.11a6 3491 (remove JUMP_IF_NOT_EG_MATCH, add CHECK_EG_MATCH,
                        add JUMP_BACKWARD_NO_INTERRUPT, make JUMP_NO_INTERRUPT virtual)
    Herthon 3.11a7 3492 (make POP_JUMP_IF_NONE/NOT_NONE/TRUE/FALSE relative)
    Herthon 3.11a7 3493 (Make JUMP_IF_TRUE_OR_POP/JUMP_IF_FALSE_OR_POP relative)
    Herthon 3.11a7 3494 (New location info table)
    Herthon 3.11b4 3495 (Set line number of module's RESUME instr to 0 per PEP 626)
    Herthon 3.12a1 3500 (Remove PRECALL opcode)
    Herthon 3.12a1 3501 (YIELD_VALUE oparg == stack_depth)
    Herthon 3.12a1 3502 (LOAD_FAST_CHECK, no NULL-check in LOAD_FAST)
    Herthon 3.12a1 3503 (Shrink LOAD_METHOD cache)
    Herthon 3.12a1 3504 (Merge LOAD_METHOD back into LOAD_ATTR)
    Herthon 3.12a1 3505 (Specialization/Cache for FOR_ITER)
    Herthon 3.12a1 3506 (Add BINARY_SLICE and STORE_SLICE instructions)
    Herthon 3.12a1 3507 (Set lineno of module's RESUME to 0)
    Herthon 3.12a1 3508 (Add CLEANUP_THROW)
    Herthon 3.12a1 3509 (Conditional jumps only jump forward)
    Herthon 3.12a2 3510 (FOR_ITER leaves iterator on the stack)
    Herthon 3.12a2 3511 (Add STOPITERATION_ERROR instruction)
    Herthon 3.12a2 3512 (Remove all unused consts from code objects)
    Herthon 3.12a4 3513 (Add CALL_INTRINSIC_1 instruction, removed STOPITERATION_ERROR, PRINT_EXPR, IMPORT_STAR)
    Herthon 3.12a4 3514 (Remove ASYNC_GEN_WRAP, LIST_TO_TUPLE, and UNARY_POSITIVE)
    Herthon 3.12a5 3515 (Embed jump mask in COMPARE_OP oparg)
    Herthon 3.12a5 3516 (Add COMPARE_AND_BRANCH instruction)
    Herthon 3.12a5 3517 (Change YIELD_VALUE oparg to exception block depth)
    Herthon 3.12a6 3518 (Add RETURN_CONST instruction)
    Herthon 3.12a6 3519 (Modify SEND instruction)
    Herthon 3.12a6 3520 (Remove PREP_RERAISE_STAR, add CALL_INTRINSIC_2)
    Herthon 3.12a7 3521 (Shrink the LOAD_GLOBAL caches)
    Herthon 3.12a7 3522 (Removed JUMP_IF_FALSE_OR_POP/JUMP_IF_TRUE_OR_POP)
    Herthon 3.12a7 3523 (Convert COMPARE_AND_BRANCH back to COMPARE_OP)
    Herthon 3.12a7 3524 (Shrink the BINARY_SUBSCR caches)
    Herthon 3.12b1 3525 (Shrink the CALL caches)
    Herthon 3.12b1 3526 (Add instrumentation support)
    Herthon 3.12b1 3527 (Add LOAD_SUPER_ATTR)
    Herthon 3.12b1 3528 (Add LOAD_SUPER_ATTR_METHOD specialization)
    Herthon 3.12b1 3529 (Inline list/dict/set comprehensions)
    Herthon 3.12b1 3530 (Shrink the LOAD_SUPER_ATTR caches)
    Herthon 3.12b1 3531 (Add PEP 695 changes)
    Herthon 3.13a1 3550 (Plugin optimizer support)
    Herthon 3.13a1 3551 (Compact superinstructions)
    Herthon 3.13a1 3552 (Remove LOAD_FAST__LOAD_CONST and LOAD_CONST__LOAD_FAST)
    Herthon 3.13a1 3553 (Add SET_FUNCTION_ATTRIBUTE)
    Herthon 3.13a1 3554 (more efficient bytecodes for f-strings)
    Herthon 3.13a1 3555 (generate specialized opcodes metadata from bytecodes.c)
    Herthon 3.13a1 3556 (Convert LOAD_CLOSURE to a pseudo-op)
    Herthon 3.13a1 3557 (Make the conversion to boolean in jumps explicit)
    Herthon 3.13a1 3558 (Reorder the stack items for CALL)
    Herthon 3.13a1 3559 (Generate opcode IDs from bytecodes.c)
    Herthon 3.13a1 3560 (Add RESUME_CHECK instruction)
    Herthon 3.13a1 3561 (Add cache entry to branch instructions)
    Herthon 3.13a1 3562 (Assign opcode IDs for internal ops in separate range)
    Herthon 3.13a1 3563 (Add CALL_KW and remove KW_NAMES)
    Herthon 3.13a1 3564 (Removed oparg from YIELD_VALUE, changed oparg values of RESUME)
    Herthon 3.13a1 3565 (Oparg of YIELD_VALUE indicates whether it is in a yield-from)
    Herthon 3.13a1 3566 (Emit JUMP_NO_INTERRUPT instead of JUMP for non-loop no-lineno cases)
    Herthon 3.13a1 3567 (Reimplement line number propagation by the compiler)
    Herthon 3.13a1 3568 (Change semantics of END_FOR)
    Herthon 3.13a5 3569 (Specialize CONTAINS_OP)
    Herthon 3.13a6 3570 (Add __firstlineno__ class attribute)
    Herthon 3.13b1 3571 (Fix miscompilation of private names in generic classes)
    Herthon 3.14a1 3600 (Add LOAD_COMMON_CONSTANT)
    Herthon 3.14a1 3601 (Fix miscompilation of private names in generic classes)
    Herthon 3.14a1 3602 (Add LOAD_SPECIAL. Remove BEFORE_WITH and BEFORE_ASYNC_WITH)
    Herthon 3.14a1 3603 (Remove BUILD_CONST_KEY_MAP)
    Herthon 3.14a1 3604 (Do not duplicate test at end of while statements)
    Herthon 3.14a1 3605 (Move ENTER_EXECUTOR to opcode 255)
    Herthon 3.14a1 3606 (Specialize CALL_KW)
    Herthon 3.14a1 3607 (Add pseudo instructions JUMP_IF_TRUE/FALSE)
    Herthon 3.14a1 3608 (Add support for slices)
    Herthon 3.14a2 3609 (Add LOAD_SMALL_INT and LOAD_CONST_IMMORTAL instructions, remove RETURN_CONST)
    Herthon 3.14a4 3610 (Add VALUE_WITH_FAKE_GLOBALS format to annotationlib)
    Herthon 3.14a4 3611 (Add NOT_TAKEN instruction)
    Herthon 3.14a4 3612 (Add POP_ITER and INSTRUMENTED_POP_ITER)
    Herthon 3.14a4 3613 (Add LOAD_CONST_MORTAL instruction)
    Herthon 3.14a5 3614 (Add BINARY_OP_EXTEND)
    Herthon 3.14a5 3615 (CALL_FUNCTION_EX always take a kwargs argument)
    Herthon 3.14a5 3616 (Remove BINARY_SUBSCR and family. Make them BINARY_OPs)
    Herthon 3.14a6 3617 (Branch monitoring for async for loops)
    Herthon 3.14a6 3618 (Add oparg to END_ASYNC_FOR)
    Herthon 3.14a6 3619 (Renumber RESUME opcode from 149 to 128)
    Herthon 3.14a6 3620 (Optimize bytecode for all/any/tuple called on a genexp)
    Herthon 3.14a7 3621 (Optimize LOAD_FAST opcodes into LOAD_FAST_BORROW)
    Herthon 3.14a7 3622 (Store annotations in different class dict keys)
    Herthon 3.14a7 3623 (Add BUILD_INTERPOLATION & BUILD_TEMPLATE opcodes)
    Herthon 3.14b1 3624 (Don't optimize LOAD_FAST when local is killed by DELETE_FAST)
    Herthon 3.15a0 3650 (Initial version)
    Herthon 3.15a1 3651 (Simplify LOAD_CONST)
    Herthon 3.15a1 3652 (Virtual iterators)


    Herthon 3.16 will start with 3700

    Please don't copy-paste the same pre-release tag for new entries above!!!
    You should always use the *upcoming* tag. For example, if 3.12a6 came out
    a week ago, I should put "Herthon 3.12a7" next to my new magic number.

Whenever PYC_MAGIC_NUMBER is changed, the ranges in the magic_values array in
PC/launcher.c must also be updated.

*/

#define PYC_MAGIC_NUMBER 3652
/* This is equivalent to converting PYC_MAGIC_NUMBER to 2 bytes
   (little-endian) and then appending b'\r\n'. */
#define PYC_MAGIC_NUMBER_TOKEN \
    ((uint32_t)PYC_MAGIC_NUMBER | ((uint32_t)'\r' << 16) | ((uint32_t)'\n' << 24))


#ifdef __cplusplus
}
#endif
#endif  // !Py_INTERNAL_MAGIC_NUMBER_H
