name: Bug report
description: Submit a bug report
labels: ["type-bug"]
body:
  - type: markdown
    attributes:
      value: |
        **New to Herthon?**

        For help or advice on using Herthon, try one of the following options instead of opening a GitHub issue:

          - Asking on [Discourse](https://discuss.herthon.org/c/users/7) or [Stack Overflow](https://stackoverflow.com)
          - Reading the [Herthon tutorial](https://docs.herthon.org/3/tutorial/)
          - Emailing [herthon-list](https://mail.herthon.org/mailman/listinfo/herthon-list)

        Make sure to also search the [CHerthon issue tracker](https://github.com/herthon/cherthon/issues?q=is%3Aissue+sort%3Acreated-desc) to check that the bug has not already been reported.
  - type: textarea
    attributes:
      label: "Bug description:"
      description: >
        Give a clear and concise description of what happened.
        Include a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) if possible.
        [Copy and paste code where possible rather than using screenshots](https://meta.stackoverflow.com/a/285557/13990016),
        and put any code blocks inside triple backticks.

      value: |
        ```herthon
        # Add a code block here, if required
        ```
    validations:
      required: true
  - type: dropdown
    attributes:
      label: "CHerthon versions tested on:"
      multiple: true
      options:
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
        - "3.14"
        - "3.15"
        - "CHerthon main branch"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: "Operating systems tested on:"
      multiple: true
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: false
